Repository 2024-Summer-Bootcamp-Team-I/Frontend, pull requests merged in 2024-07, with the labels that each got.

#15 design:검색창 퍼블리싱
  dist/assets/css/global.chunk.css
  dist/assets/js/index.js
  dist/src/pages/devtools/index.html
  dist/src/pages/newtab/index.html
  dist/src/pages/newtab/index.js
  dist/src/pages/options/index.html
  dist/src/pages/panel/index.html
  dist/src/pages/popup/index.html
  dist/src/pages/sidepanel/index.html
  src/assets/img/SearchIcon.svg
  src/components/SearchBar.tsx
  src/pages/newtab/Newtab.tsx
Labels: UI디자인

#18 design : 사이드 패널 IT/과학 탭, article에서만 열리게 설정, 팝업 아이콘 누르면 바로 사이드패널 열리게 설정
  dist/assets/css/global.chunk.css
  dist/assets/css/sidepanel.chunk.css
  dist/assets/js/index.js
  dist/assets/svg/bg_img1.chunk.svg
  dist/assets/svg/logo.chunk.svg
  dist/manifest.json
  dist/src/pages/background/index.js
  dist/src/pages/popup/index.html
  dist/src/pages/sidepanel/index.js
  manifest.js
  src/pages/background/index.ts
  src/pages/popup/index.html
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/index.tsx
Labels: 환경설정, UI디자인

#19 design:네브바 퍼블리싱
  src/assets/img/logo.png
  src/components/Navbar.tsx
  src/pages/newtab/Newtab.tsx
Labels: UI디자인

#24 design : 회원가입, 로그인 사이드패널 퍼블리싱
  src/assets/img/emailicon.svg
  src/assets/img/passwordicon.svg
  src/assets/img/usernameicon.svg
  src/components/Navbar.tsx
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/Signup.tsx
  tailwind.config.js
Labels: UI디자인

#26 design:모달창 퍼블리싱
  src/assets/img/xbutton.svg
  src/components/Info.tsx
  src/components/Modal.tsx
Labels: UI디자인

#27 design:스크랩 사이드패널 퍼블리싱
  src/assets/img/Calendar.svg
  src/assets/img/Line1.svg
  src/assets/img/ScrapIcon.svg
  src/assets/img/TV.svg
  src/assets/img/article1.svg
  src/components/BlankBoard.tsx
  src/components/ScrapBoard.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/SidePanel.tsx
Labels: UI디자인

#31 design:검증된 기사 퍼블리싱(페이지네이션 제외)
  src/assets/img/article2.svg
  src/assets/img/leftArrow.svg
  src/assets/img/percentEx.svg
  src/components/CardNews.tsx
  src/components/Pagination.tsx
  src/pages/newtab/ClassifiedNews.tsx
  src/pages/newtab/Newtab.tsx
Labels: UI디자인

#33 design: 판별 점수 원 그래프 퍼블리싱, 애니메이션
  package.json
  src/components/LiquidFillGauge.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/sidepanel/Login.tsx
  yarn.lock
Labels: UI디자인

#35 design : 검증된 기사에 그래프 추가, 1920/2560 반응형
  src/assets/img/article2.svg
  src/assets/img/percentEx.svg
  src/components/CardNews.tsx
  src/components/Navbar.tsx
  src/pages/newtab/ClassifiedNews.tsx
  src/pages/newtab/Newtab.tsx
  tailwind.config.js
Labels: UI디자인

#37 design: 피드백 사이드패널 퍼블리싱, 별점 구현
  src/assets/img/FeedbackIcon.svg
  src/assets/img/ShortcutsIcon.svg
  src/components/BlankBoard.tsx
  src/components/LeftStar.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/RatingStars.tsx
  src/components/RightStar.tsx
  src/components/TruestScoreInfo.tsx
  src/components/TrustScoreModal.tsx
  src/global.css
  src/pages/newtab/MyNews.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/sidepanel/Feedback.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현, UI디자인

#44 fix:캐러셀 수정#43
  src/components/Carousel.tsx
  src/components/Test.tsx
  src/pages/newtab/MyNews.tsx
  src/pages/newtab/Newtab.tsx
  yarn.lock
Labels: 오류수정

#42 design:파도 그래프
  src/assets/img/Polygon5.svg
  src/components/WaveGraph.tsx
  src/global.css
  src/pages/newtab/ChannelRanking.tsx
Labels: UI디자인

#48 Chore/#46
  .gitignore
  package.json
  src/global.css
  src/pages/newtab/index.tsx
  src/pages/sidepanel/Feedback.tsx
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/index.tsx
  src/queryClient.ts
  src/store.ts
  src/stores/store.ts
  vite.config.ts
  yarn.lock
Labels: 환경설정

#50 design: 본문 a,b,c로 나눠서 퍼블리싱
  .DS_Store
  src/assets/img/FeedbackIcon.svg
  src/components/AverageRating.tsx
  src/components/LeftStar.tsx
  src/components/Navbar.tsx
  src/components/RatingStars.tsx
  src/components/RightStar.tsx
  src/components/SavedNews.tsx
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/MainTextB.tsx
  src/pages/newtab/MainTextC.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/newtab/ServiceInfo.tsx
Labels: UI디자인

#52 design:사이드패널 타임라인 퍼블리싱
  package.json
  src/pages/sidepanel/Timeline.tsx
  yarn.lock
Labels: UI디자인

#54 design:모달창 퍼블리싱
  src/components/Modal.tsx
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/Signup.tsx
Labels: UI디자인

#55 fix:캐러셀 반응형 수정
  src/components/Carousel.tsx
  src/components/SavedNews.tsx
  yarn.lock
Labels: 오류수정

#58 design:파도 그래프 크기수정
  src/components/WaveGraph.tsx
  src/pages/newtab/ServiceInfo.tsx
Labels: UI디자인

#60 feat: 드래그앤드랍 기능구현, 스크랩 api연동
  manifest.js
  package.json
  src/assets/img/TrashIcon.svg
  src/axios.js
  src/components/BlankBoard.tsx
  src/components/ScrapBoard.tsx
  src/pages/content/index.ts
  src/pages/newtab/Newtab.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/index.tsx
  src/types/ItemTypes.ts
  vite.config.ts
  yarn.lock
Labels: 기능구현, 리팩토링

#62 Feat/#59 로그인 API연동
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현

#63 feat: 회원가입 api 연동
  .DS_Store
  package.json
  src/pages/sidepanel/Signup.tsx
  yarn.lock
Labels: 기능구현

#70 fix:캐러셀 위치 및 간격수정
  .DS_Store
  src/components/Carousel.tsx
Labels: 오류수정

#72 feat: maintexta 개별 조회 연동, 사이드패널간 연결
  .DS_Store
  manifest.js
  package.json
  src/components/CardNews.tsx
  src/components/Carousel.tsx
  src/components/Navbar.tsx
  src/components/SavedNews.tsx
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/MainTextB.tsx
  src/pages/newtab/MainTextC.tsx
  src/pages/newtab/MyNews.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/Signup.tsx
  src/types/ItemTypes.ts
  src/types/article.ts
  yarn.lock
Labels: 기능구현

#74 Feat/#66 뉴스 기사개수조회 API 연동
  src/components/WaveGraph.tsx
  src/pages/newtab/ServiceInfo.tsx
Labels: 기능구현

#75 Fix/#73
  manifest.js
  package-lock.json
  package.json
  public/Logo1.png
  public/icon-128.png
  public/icon-34.png
  src/assets/img/Logo.svg
  src/assets/img/Logo3.png
  src/components/Carousel.tsx
  src/components/Navbar.tsx
  src/pages/content/index.ts
  src/pages/devtools/index.ts
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/index.html
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/Signup.tsx
Labels: 오류수정, UI디자인

#80 design: LottieFiles 애니메이션 mainText A 로딩창에 적용
  package.json
  src/assets/img/loading001.json
  src/assets/img/loading002.json
  src/assets/img/loading003.json
  src/assets/img/loading004.json
  src/pages/newtab/MainTextA.tsx
  yarn.lock
Labels: UI디자인

#81 feat:타임라인 기능구현
  .DS_Store
  public/manifest.json
  src/pages/background/index.ts
  src/pages/content/index.ts
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/Timeline.tsx
Labels: 기능구현

#84 feat:사이드패널 연결
  public/manifest.json
  src/pages/background/index.ts
  src/pages/content/index.ts
  src/pages/sidepanel/SidePanel.tsx
  src/pages/sidepanel/Timeline.tsx
Labels: 기능구현

#88 Fix/#85 NavBar 및 기사 날짜 형식 수정
  src/components/CardNews.tsx
  src/components/Carousel.tsx
  src/components/Navbar.tsx
  src/components/ScrapBoard.tsx
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/MainTextC.tsx
  utils/formatDate.tsx
Labels: 오류수정

#89 Fix:캐러셀 슬라이드 크기조정, 글래스모피즘, 판별통계 탭 글자 크기수정(4xl)
  src/components/Carousel.tsx
  src/components/WaveGraph.tsx
  src/components/WaveModal.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/newtab/ServiceInfo.tsx
Labels: 오류수정

#91 Fix/#86
  src/components/Carousel.tsx
  src/pages/newtab/MainTextC.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/newtab/ServiceInfo.tsx
  src/pages/sidepanel/Scrap.tsx
Labels: 오류수정

#93 fix:타임라인 디자인 수정
  src/assets/img/TimelineIcon.svg
  src/pages/sidepanel/Timeline.tsx
Labels: 오류수정

#97 feat:스크랩 페이지 검색기능 구현
  src/components/Carousel.tsx
  src/components/Navbar.tsx
  src/components/SavedNews.tsx
  src/components/SearchBar.tsx
  src/pages/newtab/MyNews.tsx
Labels: 기능구현

#99 feat: 판별된 기사 검색 추가
  src/pages/newtab/RelatedNews.tsx
Labels: 기능구현

#101 Fix:api url변경, 오류 수정
  dist.zip
  package.json
  pnpm-lock.yaml
  src/components/Carousel.tsx
  src/components/ScrapBoard.tsx
  src/pages/content/index.ts
  src/pages/content/ui/index.tsx
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/MainTextC.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/newtab/ServiceInfo.tsx
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/Signup.tsx
  src/pages/sidepanel/Timeline.tsx
  utils/plugins/make-manifest.ts
  yarn.lock
Labels: 오류수정

#102 Design/#94
  src/assets/img/Ex_Timeline.svg
  src/assets/img/Ex_article.png
  src/assets/img/Ex_extension_scrappng.png
  src/assets/img/Ex_verified.png
  src/assets/img/WhaleIcon.svg
  src/assets/img/bg_onboarding.svg
  src/assets/img/bg_onboarding_3222.svg
  src/assets/img/dashLineForScore.svg
  src/assets/img/dashLineForSummary.svg
  src/assets/img/githubIcon.svg
  src/assets/img/moveToDown.svg
  src/assets/img/moveToTop.svg
  src/components/Navbar.tsx
  src/pages/newtab/Newtab.tsx
  src/pages/newtab/OnBorading.tsx
Labels: UI디자인

#104 fix: url localhost로 변경
  package.json
  src/components/Carousel.tsx
  src/components/ScrapBoard.tsx
  src/pages/content/index.ts
  src/pages/newtab/MainTextA.tsx
  src/pages/newtab/MainTextC.tsx
  src/pages/newtab/RelatedNews.tsx
  src/pages/newtab/ServiceInfo.tsx
  src/pages/sidepanel/Login.tsx
  src/pages/sidepanel/Scrap.tsx
  src/pages/sidepanel/Signup.tsx
Labels: 오류수정
